name: Build and release single binary packages

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

concurrency:
  group: ci-${{ github.workflow }}
  cancel-in-progress: true

env:
  BIN_NAME: elasticsearch-faker
  DIST_DIR_NAME: dist

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.8]
        os: [ubuntu-18.04, ubuntu-20.04]
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pip
        run: python -m pip install --upgrade --disable-pip-version-check "pip>=21.1"

      - name: Get pip cache dir
        id: pip-cache
        run: echo "::set-output name=dir::$(pip cache dir)"

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: |
            ${{ steps.pip-cache.outputs.dir }}
            ./.tox
          key: ${{ matrix.os }}-${{ matrix.python-version }}-pip-${{ hashFiles('setup.py', '**/requirements.txt') }}
          restore-keys: |
            ${{ matrix.os }}-${{ matrix.python-version }}-pip-

      - name: Get version
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Build deb package
        id: build_deb_package
        run: |
          make setup-deb-build
          ./build_deb_package.sh
          ls -lh ${DIST_DIR_NAME}/*

          echo "::set-output name=dist_linux_files::$(find ${DIST_DIR_NAME}/${BIN_NAME}_*)"

      - uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: ${{ env.DIST_DIR_NAME }}/${{ env.BIN_NAME }}_*
          if-no-files-found: error
          retention-days: 1

      - name: Release binary packages
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ${{ steps.build_deb_package.outputs.dist_linux_files }}

  calc-hash:
    needs: [build-and-release]
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      SHA_DIR: sha
      SHA_TEXT_FILE: elasticsearch-faker_sha256.txt

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: binaries
          path: ${{ env.DIST_DIR_NAME }}

      - name: Calculate checksums of binary packages
        id: calc_checksum
        run: |
          set -x

          mkdir -p "$SHA_DIR"
          cd "$DIST_DIR_NAME"
          sha256sum ${BIN_NAME}_* > "../${SHA_DIR}/${SHA_TEXT_FILE}"

          echo "::set-output name=filename::${SHA_DIR}/${SHA_TEXT_FILE}"

      - uses: actions/upload-artifact@v2
        with:
          name: shasum
          path: ${{ env.SHA_DIR }}
          if-no-files-found: error
          retention-days: 1

      - name: Release checksum
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ${{ steps.calc_checksum.outputs.filename }}
