name: Build and release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.8]
        os: [ubuntu-18.04, ubuntu-20.04]
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pip
        run: python -m pip install --upgrade --disable-pip-version-check "pip>=21.1" distro

      - name: Get pip cache dir
        id: pip-cache
        run: echo "::set-output name=dir::$(pip cache dir)"

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: |
            ${{ steps.pip-cache.outputs.dir }}
            ./.tox
          key: ${{ matrix.os }}-${{ matrix.python-version }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ matrix.os }}-${{ matrix.python-version }}-pip-

      - name: Get version
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Build deb package
        id: build_deb_package
        run: |
          ./build_deb_package.sh
          codename=$(python -m distro --json | jq --raw-output .codename)
          checksum_filename=sha256sum_${codename}_amd64.txt

          echo "codename=${codename}"

          sha256sum ${{ steps.build_deb_package.outputs.dist_filepath_amd64 }} > "$checksum_filename"

          echo "::debug::checksum=$checksum_filename"

          echo "::set-output name=checksum_file::$checksum_filename"
          echo "::set-output name=dist_filepath_amd64::$(find dist/elasticsearch-faker-*_*.*.*_amd64.deb)"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ steps.build_deb_package.outputs.dist_filepath_amd64 }}
            ${{ steps.build_deb_package.outputs.checksum_file }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
