name: Build and publish Docker images

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build-docker-images:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: "ghcr.io"
      OWNER: "thombashi"
      REPO: "elasticsearch-faker"

    steps:
      - uses: actions/checkout@v2

      - name: Extract version
        id: extract-version
        run: echo "::set-output name=version::$(./docker/extract_version.sh)"

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Package Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login "$REGISTRY" -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker images - es7
        working-directory: docker
        env:
          ES_FAKER_VERSION: ${{ steps.extract-version.outputs.version }}
          EXTRAS: es7
        run: |
          IMAGE_TAG=${REGISTRY}/${OWNER}/${REPO}:${ES_FAKER_VERSION}-${EXTRAS}

          docker buildx build \
            -t "$IMAGE_TAG" \
            --platform=linux/amd64,linux/arm64 \
            --build-arg version=$ES_FAKER_VERSION \
            --build-arg extras=$EXTRAS \
            --push .
