name: Create and publish a Docker image

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: thombashi
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: make docker-build
        working-directory: docker

      - name: Push Docker image
        if: startsWith(github.ref, 'refs/tags/')
        run: make docker-push
        working-directory: docker
