name: Create and publish a Docker image

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: thombashi
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        working-directory: docker
        run: |
          # wait for PyPI to be reflected the package release
          sleep 30

          # build with retries
          MAX_ATTEMPT=30
          BASE_SLEEP=1
          CMD="make docker-build"

          $CMD && exit 0

          for attempt_num in $(seq $MAX_ATTEMPT); do
              SLEEP=$(echo "$BASE_SLEEP * $attempt_num" | bc)
              echo "'$CMD' failed. retrying in $SLEEP seconds..." 1>&2
              sleep $SLEEP

              $CMD && exit 0
          done

          exit 1

      - name: Push Docker image
        if: startsWith(github.ref, 'refs/tags/')
        run: make docker-push
        working-directory: docker
