name: Build and release single binary packages

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

concurrency:
  group: ci-${{ github.workflow }}
  cancel-in-progress: true

env:
  BIN_NAME: elasticsearch-faker
  DIST_DIR_NAME: dist

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.10"]
        os: [ubuntu-20.04, ubuntu-22.04]
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: |
            setup.py
            **/*requirements.txt
            tox.ini

      - name: Install pip
        run: python -m pip install --upgrade --disable-pip-version-check "pip>=21.1"

      - name: Setup build
        run: make setup-deb-build

      - name: Build deb package - es8
        run: |
          ./build_deb_package.sh es8
          ls -lh ${DIST_DIR_NAME}/*

      - uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: ${{ env.DIST_DIR_NAME }}/${{ env.BIN_NAME }}_*
          if-no-files-found: error
          retention-days: 1

      - name: Release binary packages
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ${{ env.DIST_DIR_NAME }}/${{ env.BIN_NAME }}_*

  calc-hash:
    needs: [build-and-release]
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      SHA_DIR: sha
      SHA_TEXT_FILE: elasticsearch-faker_sha256.txt

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: binaries
          path: ${{ env.DIST_DIR_NAME }}

      - name: Calculate checksums of binary packages
        id: calc_checksum
        run: |
          set -x

          mkdir -p "$SHA_DIR"
          cd "$DIST_DIR_NAME"
          sha256sum ${BIN_NAME}_* > "../${SHA_DIR}/${SHA_TEXT_FILE}"

          echo "filename=${SHA_DIR}/${SHA_TEXT_FILE}" >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@v3
        with:
          name: shasum
          path: ${{ env.SHA_DIR }}
          if-no-files-found: error
          retention-days: 1

      - name: Release checksum
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ${{ steps.calc_checksum.outputs.filename }}
